// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package secondmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the SecondModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getSalesDeletedBuilder(
		myfirstmodule.proxies.SalesTrackingTable _salesTrackingTable
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SecondModule.GetSalesDeleted");
		builder = builder.withParam("SalesTrackingTable", _salesTrackingTable);
		return builder;
	}

	public static boolean getSalesDeleted(
		IContext context,
		myfirstmodule.proxies.SalesTrackingTable _salesTrackingTable
	)
	{
		Object result = getSalesDeletedBuilder(
				_salesTrackingTable
			)
			.execute(context);
		return (boolean) result;
	}
}
