// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Customers implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Customers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		BirthDate("BirthDate"),
		MaritialStatus("MaritialStatus"),
		Gender("Gender"),
		MailAddress("MailAddress"),
		PhoneNumber("PhoneNumber"),
		AverageYearlyIncome("AverageYearlyIncome"),
		AverageSalesOrderQuantity("AverageSalesOrderQuantity");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Customers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customersMendixObject)
	{
		if (customersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, customersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.customersMendixObject = customersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Customers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Customers(context, mendixObject);
	}

	public static myfirstmodule.proxies.Customers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Customers.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Customers> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Customers.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of BirthDate
	 */
	public final java.util.Date getBirthDate()
	{
		return getBirthDate(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthDate
	 */
	public final java.util.Date getBirthDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.BirthDate.toString());
	}

	/**
	 * Set value of BirthDate
	 * @param birthdate
	 */
	public final void setBirthDate(java.util.Date birthdate)
	{
		setBirthDate(getContext(), birthdate);
	}

	/**
	 * Set value of BirthDate
	 * @param context
	 * @param birthdate
	 */
	public final void setBirthDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birthdate)
	{
		getMendixObject().setValue(context, MemberNames.BirthDate.toString(), birthdate);
	}

	/**
	 * Get value of MaritialStatus
	 * @param maritialstatus
	 */
	public final myfirstmodule.proxies.MaritialStatus getMaritialStatus()
	{
		return getMaritialStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of MaritialStatus
	 */
	public final myfirstmodule.proxies.MaritialStatus getMaritialStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MaritialStatus.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.MaritialStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MaritialStatus
	 * @param maritialstatus
	 */
	public final void setMaritialStatus(myfirstmodule.proxies.MaritialStatus maritialstatus)
	{
		setMaritialStatus(getContext(), maritialstatus);
	}

	/**
	 * Set value of MaritialStatus
	 * @param context
	 * @param maritialstatus
	 */
	public final void setMaritialStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.MaritialStatus maritialstatus)
	{
		if (maritialstatus != null) {
			getMendixObject().setValue(context, MemberNames.MaritialStatus.toString(), maritialstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MaritialStatus.toString(), null);
		}
	}

	/**
	 * Get value of Gender
	 * @param gender
	 */
	public final myfirstmodule.proxies.Gender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final myfirstmodule.proxies.Gender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(myfirstmodule.proxies.Gender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Gender gender)
	{
		if (gender != null) {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
		}
	}

	/**
	 * @return value of MailAddress
	 */
	public final java.lang.String getMailAddress()
	{
		return getMailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of MailAddress
	 */
	public final java.lang.String getMailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MailAddress.toString());
	}

	/**
	 * Set value of MailAddress
	 * @param mailaddress
	 */
	public final void setMailAddress(java.lang.String mailaddress)
	{
		setMailAddress(getContext(), mailaddress);
	}

	/**
	 * Set value of MailAddress
	 * @param context
	 * @param mailaddress
	 */
	public final void setMailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mailaddress)
	{
		getMendixObject().setValue(context, MemberNames.MailAddress.toString(), mailaddress);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of AverageYearlyIncome
	 */
	public final java.math.BigDecimal getAverageYearlyIncome()
	{
		return getAverageYearlyIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageYearlyIncome
	 */
	public final java.math.BigDecimal getAverageYearlyIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AverageYearlyIncome.toString());
	}

	/**
	 * Set value of AverageYearlyIncome
	 * @param averageyearlyincome
	 */
	public final void setAverageYearlyIncome(java.math.BigDecimal averageyearlyincome)
	{
		setAverageYearlyIncome(getContext(), averageyearlyincome);
	}

	/**
	 * Set value of AverageYearlyIncome
	 * @param context
	 * @param averageyearlyincome
	 */
	public final void setAverageYearlyIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal averageyearlyincome)
	{
		getMendixObject().setValue(context, MemberNames.AverageYearlyIncome.toString(), averageyearlyincome);
	}

	/**
	 * @return value of AverageSalesOrderQuantity
	 */
	public final java.lang.Integer getAverageSalesOrderQuantity()
	{
		return getAverageSalesOrderQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageSalesOrderQuantity
	 */
	public final java.lang.Integer getAverageSalesOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AverageSalesOrderQuantity.toString());
	}

	/**
	 * Set value of AverageSalesOrderQuantity
	 * @param averagesalesorderquantity
	 */
	public final void setAverageSalesOrderQuantity(java.lang.Integer averagesalesorderquantity)
	{
		setAverageSalesOrderQuantity(getContext(), averagesalesorderquantity);
	}

	/**
	 * Set value of AverageSalesOrderQuantity
	 * @param context
	 * @param averagesalesorderquantity
	 */
	public final void setAverageSalesOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer averagesalesorderquantity)
	{
		getMendixObject().setValue(context, MemberNames.AverageSalesOrderQuantity.toString(), averagesalesorderquantity);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Customers that = (myfirstmodule.proxies.Customers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
