// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class SalesTrackingTableTemporary implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesTrackingTableTemporaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.SalesTrackingTableTemporary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SalesID("SalesID"),
		OrderQuantity("OrderQuantity"),
		UnitPrice("UnitPrice"),
		DiscountAmount("DiscountAmount"),
		ProductStandardCost("ProductStandardCost"),
		TaxAmt("TaxAmt"),
		OrderDate("OrderDate"),
		ShipDate("ShipDate"),
		DueDate("DueDate"),
		SalesTrackingTableTemporary_Customers("MyFirstModule.SalesTrackingTableTemporary_Customers"),
		SalesTrackingTableTemporary_Products("MyFirstModule.SalesTrackingTableTemporary_Products"),
		SalesTrackingTableTemporary_Locations("MyFirstModule.SalesTrackingTableTemporary_Locations"),
		SalesTrackingTableTemporary_SalesPersons("MyFirstModule.SalesTrackingTableTemporary_SalesPersons");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesTrackingTableTemporary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SalesTrackingTableTemporary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesTrackingTableTemporaryMendixObject)
	{
		if (salesTrackingTableTemporaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, salesTrackingTableTemporaryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.salesTrackingTableTemporaryMendixObject = salesTrackingTableTemporaryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.SalesTrackingTableTemporary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.SalesTrackingTableTemporary(context, mendixObject);
	}

	public static myfirstmodule.proxies.SalesTrackingTableTemporary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.SalesTrackingTableTemporary.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.SalesTrackingTableTemporary> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.SalesTrackingTableTemporary.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SalesID
	 */
	public final java.lang.Long getSalesID()
	{
		return getSalesID(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesID
	 */
	public final java.lang.Long getSalesID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SalesID.toString());
	}

	/**
	 * Set value of SalesID
	 * @param salesid
	 */
	public final void setSalesID(java.lang.Long salesid)
	{
		setSalesID(getContext(), salesid);
	}

	/**
	 * Set value of SalesID
	 * @param context
	 * @param salesid
	 */
	public final void setSalesID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long salesid)
	{
		getMendixObject().setValue(context, MemberNames.SalesID.toString(), salesid);
	}

	/**
	 * @return value of OrderQuantity
	 */
	public final java.lang.Integer getOrderQuantity()
	{
		return getOrderQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderQuantity
	 */
	public final java.lang.Integer getOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OrderQuantity.toString());
	}

	/**
	 * Set value of OrderQuantity
	 * @param orderquantity
	 */
	public final void setOrderQuantity(java.lang.Integer orderquantity)
	{
		setOrderQuantity(getContext(), orderquantity);
	}

	/**
	 * Set value of OrderQuantity
	 * @param context
	 * @param orderquantity
	 */
	public final void setOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orderquantity)
	{
		getMendixObject().setValue(context, MemberNames.OrderQuantity.toString(), orderquantity);
	}

	/**
	 * @return value of UnitPrice
	 */
	public final java.math.BigDecimal getUnitPrice()
	{
		return getUnitPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of UnitPrice
	 */
	public final java.math.BigDecimal getUnitPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UnitPrice.toString());
	}

	/**
	 * Set value of UnitPrice
	 * @param unitprice
	 */
	public final void setUnitPrice(java.math.BigDecimal unitprice)
	{
		setUnitPrice(getContext(), unitprice);
	}

	/**
	 * Set value of UnitPrice
	 * @param context
	 * @param unitprice
	 */
	public final void setUnitPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal unitprice)
	{
		getMendixObject().setValue(context, MemberNames.UnitPrice.toString(), unitprice);
	}

	/**
	 * @return value of DiscountAmount
	 */
	public final java.math.BigDecimal getDiscountAmount()
	{
		return getDiscountAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of DiscountAmount
	 */
	public final java.math.BigDecimal getDiscountAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DiscountAmount.toString());
	}

	/**
	 * Set value of DiscountAmount
	 * @param discountamount
	 */
	public final void setDiscountAmount(java.math.BigDecimal discountamount)
	{
		setDiscountAmount(getContext(), discountamount);
	}

	/**
	 * Set value of DiscountAmount
	 * @param context
	 * @param discountamount
	 */
	public final void setDiscountAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal discountamount)
	{
		getMendixObject().setValue(context, MemberNames.DiscountAmount.toString(), discountamount);
	}

	/**
	 * @return value of ProductStandardCost
	 */
	public final java.math.BigDecimal getProductStandardCost()
	{
		return getProductStandardCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductStandardCost
	 */
	public final java.math.BigDecimal getProductStandardCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProductStandardCost.toString());
	}

	/**
	 * Set value of ProductStandardCost
	 * @param productstandardcost
	 */
	public final void setProductStandardCost(java.math.BigDecimal productstandardcost)
	{
		setProductStandardCost(getContext(), productstandardcost);
	}

	/**
	 * Set value of ProductStandardCost
	 * @param context
	 * @param productstandardcost
	 */
	public final void setProductStandardCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal productstandardcost)
	{
		getMendixObject().setValue(context, MemberNames.ProductStandardCost.toString(), productstandardcost);
	}

	/**
	 * @return value of TaxAmt
	 */
	public final java.math.BigDecimal getTaxAmt()
	{
		return getTaxAmt(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxAmt
	 */
	public final java.math.BigDecimal getTaxAmt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TaxAmt.toString());
	}

	/**
	 * Set value of TaxAmt
	 * @param taxamt
	 */
	public final void setTaxAmt(java.math.BigDecimal taxamt)
	{
		setTaxAmt(getContext(), taxamt);
	}

	/**
	 * Set value of TaxAmt
	 * @param context
	 * @param taxamt
	 */
	public final void setTaxAmt(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal taxamt)
	{
		getMendixObject().setValue(context, MemberNames.TaxAmt.toString(), taxamt);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of ShipDate
	 */
	public final java.util.Date getShipDate()
	{
		return getShipDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ShipDate
	 */
	public final java.util.Date getShipDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ShipDate.toString());
	}

	/**
	 * Set value of ShipDate
	 * @param shipdate
	 */
	public final void setShipDate(java.util.Date shipdate)
	{
		setShipDate(getContext(), shipdate);
	}

	/**
	 * Set value of ShipDate
	 * @param context
	 * @param shipdate
	 */
	public final void setShipDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date shipdate)
	{
		getMendixObject().setValue(context, MemberNames.ShipDate.toString(), shipdate);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SalesTrackingTableTemporary_Customers
	 */
	public final myfirstmodule.proxies.Customers getSalesTrackingTableTemporary_Customers() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTableTemporary_Customers(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTableTemporary_Customers
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Customers getSalesTrackingTableTemporary_Customers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Customers result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTableTemporary_Customers.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Customers.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SalesTrackingTableTemporary_Customers
	 * @param salestrackingtabletemporary_customers
	 */
	public final void setSalesTrackingTableTemporary_Customers(myfirstmodule.proxies.Customers salestrackingtabletemporary_customers)
	{
		setSalesTrackingTableTemporary_Customers(getContext(), salestrackingtabletemporary_customers);
	}

	/**
	 * Set value of SalesTrackingTableTemporary_Customers
	 * @param context
	 * @param salestrackingtabletemporary_customers
	 */
	public final void setSalesTrackingTableTemporary_Customers(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Customers salestrackingtabletemporary_customers)
	{
		if (salestrackingtabletemporary_customers == null) {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_Customers.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_Customers.toString(), salestrackingtabletemporary_customers.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SalesTrackingTableTemporary_Products
	 */
	public final myfirstmodule.proxies.Products getSalesTrackingTableTemporary_Products() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTableTemporary_Products(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTableTemporary_Products
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Products getSalesTrackingTableTemporary_Products(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Products result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTableTemporary_Products.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Products.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SalesTrackingTableTemporary_Products
	 * @param salestrackingtabletemporary_products
	 */
	public final void setSalesTrackingTableTemporary_Products(myfirstmodule.proxies.Products salestrackingtabletemporary_products)
	{
		setSalesTrackingTableTemporary_Products(getContext(), salestrackingtabletemporary_products);
	}

	/**
	 * Set value of SalesTrackingTableTemporary_Products
	 * @param context
	 * @param salestrackingtabletemporary_products
	 */
	public final void setSalesTrackingTableTemporary_Products(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Products salestrackingtabletemporary_products)
	{
		if (salestrackingtabletemporary_products == null) {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_Products.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_Products.toString(), salestrackingtabletemporary_products.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SalesTrackingTableTemporary_Locations
	 */
	public final myfirstmodule.proxies.Locations getSalesTrackingTableTemporary_Locations() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTableTemporary_Locations(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTableTemporary_Locations
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Locations getSalesTrackingTableTemporary_Locations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Locations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTableTemporary_Locations.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Locations.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SalesTrackingTableTemporary_Locations
	 * @param salestrackingtabletemporary_locations
	 */
	public final void setSalesTrackingTableTemporary_Locations(myfirstmodule.proxies.Locations salestrackingtabletemporary_locations)
	{
		setSalesTrackingTableTemporary_Locations(getContext(), salestrackingtabletemporary_locations);
	}

	/**
	 * Set value of SalesTrackingTableTemporary_Locations
	 * @param context
	 * @param salestrackingtabletemporary_locations
	 */
	public final void setSalesTrackingTableTemporary_Locations(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Locations salestrackingtabletemporary_locations)
	{
		if (salestrackingtabletemporary_locations == null) {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_Locations.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_Locations.toString(), salestrackingtabletemporary_locations.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SalesTrackingTableTemporary_SalesPersons
	 */
	public final myfirstmodule.proxies.SalesPersons getSalesTrackingTableTemporary_SalesPersons() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTableTemporary_SalesPersons(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTableTemporary_SalesPersons
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.SalesPersons getSalesTrackingTableTemporary_SalesPersons(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.SalesPersons result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTableTemporary_SalesPersons.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.SalesPersons.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SalesTrackingTableTemporary_SalesPersons
	 * @param salestrackingtabletemporary_salespersons
	 */
	public final void setSalesTrackingTableTemporary_SalesPersons(myfirstmodule.proxies.SalesPersons salestrackingtabletemporary_salespersons)
	{
		setSalesTrackingTableTemporary_SalesPersons(getContext(), salestrackingtabletemporary_salespersons);
	}

	/**
	 * Set value of SalesTrackingTableTemporary_SalesPersons
	 * @param context
	 * @param salestrackingtabletemporary_salespersons
	 */
	public final void setSalesTrackingTableTemporary_SalesPersons(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SalesPersons salestrackingtabletemporary_salespersons)
	{
		if (salestrackingtabletemporary_salespersons == null) {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_SalesPersons.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SalesTrackingTableTemporary_SalesPersons.toString(), salestrackingtabletemporary_salespersons.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesTrackingTableTemporaryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.SalesTrackingTableTemporary that = (myfirstmodule.proxies.SalesTrackingTableTemporary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
