// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package secondmodule.proxies;

public class SalesDeletedHistory implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesDeletedHistoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SecondModule.SalesDeletedHistory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SalesId("SalesId"),
		OrderQuantify("OrderQuantify");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesDeletedHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SalesDeletedHistory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesDeletedHistoryMendixObject)
	{
		if (salesDeletedHistoryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, salesDeletedHistoryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.salesDeletedHistoryMendixObject = salesDeletedHistoryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static secondmodule.proxies.SalesDeletedHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new secondmodule.proxies.SalesDeletedHistory(context, mendixObject);
	}

	public static secondmodule.proxies.SalesDeletedHistory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return secondmodule.proxies.SalesDeletedHistory.initialize(context, mendixObject);
	}

	public static java.util.List<secondmodule.proxies.SalesDeletedHistory> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> secondmodule.proxies.SalesDeletedHistory.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SalesId
	 */
	public final java.lang.Integer getSalesId()
	{
		return getSalesId(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesId
	 */
	public final java.lang.Integer getSalesId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SalesId.toString());
	}

	/**
	 * Set value of SalesId
	 * @param salesid
	 */
	public final void setSalesId(java.lang.Integer salesid)
	{
		setSalesId(getContext(), salesid);
	}

	/**
	 * Set value of SalesId
	 * @param context
	 * @param salesid
	 */
	public final void setSalesId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer salesid)
	{
		getMendixObject().setValue(context, MemberNames.SalesId.toString(), salesid);
	}

	/**
	 * @return value of OrderQuantify
	 */
	public final java.lang.Integer getOrderQuantify()
	{
		return getOrderQuantify(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderQuantify
	 */
	public final java.lang.Integer getOrderQuantify(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OrderQuantify.toString());
	}

	/**
	 * Set value of OrderQuantify
	 * @param orderquantify
	 */
	public final void setOrderQuantify(java.lang.Integer orderquantify)
	{
		setOrderQuantify(getContext(), orderquantify);
	}

	/**
	 * Set value of OrderQuantify
	 * @param context
	 * @param orderquantify
	 */
	public final void setOrderQuantify(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orderquantify)
	{
		getMendixObject().setValue(context, MemberNames.OrderQuantify.toString(), orderquantify);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesDeletedHistoryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final secondmodule.proxies.SalesDeletedHistory that = (secondmodule.proxies.SalesDeletedHistory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
